/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSubredditIndexRouteImport } from './routes/r.$subreddit.index'
import { Route as RSubredditCommentsPostIdSplatRouteImport } from './routes/r.$subreddit.comments.$postId.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSubredditIndexRoute = RSubredditIndexRouteImport.update({
  id: '/r/$subreddit/',
  path: '/r/$subreddit/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSubredditCommentsPostIdSplatRoute =
  RSubredditCommentsPostIdSplatRouteImport.update({
    id: '/r/$subreddit/comments/$postId/$',
    path: '/r/$subreddit/comments/$postId/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r/$subreddit': typeof RSubredditIndexRoute
  '/r/$subreddit/comments/$postId/$': typeof RSubredditCommentsPostIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r/$subreddit': typeof RSubredditIndexRoute
  '/r/$subreddit/comments/$postId/$': typeof RSubredditCommentsPostIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/r/$subreddit/': typeof RSubredditIndexRoute
  '/r/$subreddit/comments/$postId/$': typeof RSubredditCommentsPostIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/r/$subreddit' | '/r/$subreddit/comments/$postId/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/r/$subreddit' | '/r/$subreddit/comments/$postId/$'
  id: '__root__' | '/' | '/r/$subreddit/' | '/r/$subreddit/comments/$postId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RSubredditIndexRoute: typeof RSubredditIndexRoute
  RSubredditCommentsPostIdSplatRoute: typeof RSubredditCommentsPostIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$subreddit/': {
      id: '/r/$subreddit/'
      path: '/r/$subreddit'
      fullPath: '/r/$subreddit'
      preLoaderRoute: typeof RSubredditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$subreddit/comments/$postId/$': {
      id: '/r/$subreddit/comments/$postId/$'
      path: '/r/$subreddit/comments/$postId/$'
      fullPath: '/r/$subreddit/comments/$postId/$'
      preLoaderRoute: typeof RSubredditCommentsPostIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RSubredditIndexRoute: RSubredditIndexRoute,
  RSubredditCommentsPostIdSplatRoute: RSubredditCommentsPostIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
